### ISSUE TITLE
music_478/r_0.wav is missing

### ISSUE THREAD

**Issue by Baiiiiiiiiii** [DanielLin94144/StyleTalk#1]
Hi,

I found that music_478/r_0.wav is missing in audio.tar.gz.
Could you please add it to the audio.tar.gz?

Thank you.

**Comment by DanielLin94144** [comment]
Hi @Baiiiiiiiiii , thanks for pointing out the issue. 
I update the google drive link in the readme. Now the audio.tar.gz should contain all the audio.
